/* ATELIER demo store — all interactions run locally in the browser. */
document.addEventListener('DOMContentLoaded', () => {
  const CART_KEY = 'atelier-demo-cart';
  const USER_KEY = 'atelier-demo-user';
  const money = new Intl.NumberFormat('es-PY');
  const formatPrice = value => `₲${money.format(value)}`;
  const readPrice = value => Number(String(value).replace(/[^0-9]/g, '')) || 0;
  const getCart = () => { try { return JSON.parse(localStorage.getItem(CART_KEY)) || []; } catch { return []; } };
  const saveCart = cart => localStorage.setItem(CART_KEY, JSON.stringify(cart));

  const nav = document.querySelector('.shop-nav');
  const page = location.pathname.split('/').pop() || 'index.html';
  const active = name => page === name ? 'active' : '';
  if (nav) nav.innerHTML = `
    <a class="${active('index.html')}" href="index.html">Inicio</a>
    <div class="nav-group"><a class="${active('women.html')}" href="women.html">Mujer</a><button class="nav-subtoggle" aria-label="Ver categorías de mujer">⌄</button><div class="nav-submenu"><b>Mujer</b><a href="women.html#remeras">Remeras & tops</a><a href="women.html#camisas">Camisas</a><a href="women.html#buzos">Buzos & abrigos</a><a href="women.html#denim">Denim</a></div></div>
    <div class="nav-group"><a class="${active('men.html')}" href="men.html">Hombre</a><button class="nav-subtoggle" aria-label="Ver categorías de hombre">⌄</button><div class="nav-submenu"><b>Hombre</b><a href="men.html#remeras">Remeras & polos</a><a href="men.html#camisas">Camisas</a><a href="men.html#buzos">Buzos & abrigos</a><a href="men.html#denim">Denim</a></div></div>
    <div class="nav-group"><a class="${active('kids.html')}" href="kids.html">Niños</a><button class="nav-subtoggle" aria-label="Ver categorías de niños">⌄</button><div class="nav-submenu"><b>Niños</b><a href="kids.html#remeras">Remeras</a><a href="kids.html#camisas">Camisas</a><a href="kids.html#buzos">Buzos & conjuntos</a><a href="kids.html#denim">Denim</a></div></div>`;
  const headerTools = document.querySelector('.shop-tools');
  if (headerTools) headerTools.innerHTML = `<button class="tool shop-menu" type="button" aria-label="Abrir menú" aria-expanded="false">☰</button><button class="tool account-button" type="button" aria-label="Iniciar sesión">◉</button><button class="tool cart-count" type="button" aria-label="Abrir bolso">0</button>`;

  // Fotos oficiales de producto VDR: prendas aisladas, sin modelos ni imágenes aleatorias.
  const productPhotos = [
    'https://vdrstore.com/web/product/medium/202509/af7c51f9a8dc050f2c90081bacdcb47d.jpg',
    'https://vdrstore.com/web/product/medium/202509/e8c187d901077cbd5711045fb1b1ce97.jpg',
    'https://vdrstore.com/web/product/medium/202509/39e18708886e30a03b9cd62082ede511.jpg',
    'https://vdrstore.com/web/product/medium/202502/70ef62f3d70498abd0127644a4dd844f.jpg',
    'https://vdrstore.com/web/product/medium/202509/1dc04d673841d873c10adb4d28a0c657.jpg',
    'https://vdrstore.com/web/product/medium/202509/c731542422038b2c81dd375e7885c71a.jpg',
    'https://vdrstore.com/web/product/medium/202502/d940455c55e151b760b521d7931208a0.jpg',
    'https://vdrstore.com/web/product/medium/202409/ff295b81143441126e2c57451122291e.jpg'
  ];
  const collectionProducts = {
    'women.html': {
      label: 'Colección Mujer',
      categories: [['vestidos', 'Vestidos & faldas'], ['blusas', 'Blusas & camisas'], ['denim', 'Denim & pantalones'], ['abrigos', 'Tejidos & abrigos']],
      items: [['vestidos', 'Vestido Amalia', 'Corte fluido y caída suave', '₲329.000', 'https://nyramode.shop/cdn/shop/files/create-square-product-showcase-images-for-a-women-s-dropshipping-brand-nyramode-show-trending-fashion-items-like-dresses-hoodies-earrings-handbags-clean-white-background-realistic-sha.png?v=1761758584&width=3840'], ['vestidos', 'Falda Siena', 'Línea midi para todos los días', '₲219.000', 'https://www.dailylook.com/images/lifestyle/DL-9579_V1.jpg'], ['blusas', 'Blusa Lía', 'Tejido liviano de textura suave', '₲189.000', 'https://cdn.vestiai.com.br/website/blog/white-background-photos-why-they-work/featuredImage.webp'], ['blusas', 'Camisa Alma', 'Algodón fresco de calce relajado', '₲249.000', 'https://www.threadicated.com.au/cdn/shop/files/womens-stylish-clothes-flat-lay_2048x2048.jpg?v=1722392326'], ['denim', 'Jean Nube', 'Denim recto de tiro alto', '₲269.000', 'https://v3b.fal.media/files/b/0a86cab9/f1_aPdcIF0hwuKKn1SXZV.jpg'], ['denim', 'Pantalón Duna', 'Sastrería ligera y cómoda', '₲279.000', 'https://store.air-closet.com/cdn/shop/collections/Frame_38.png?v=1756729907&width=1500'], ['abrigos', 'Sweater Cora', 'Punto suave para entretiempo', '₲229.000', 'https://stfl.it/covers/cat_ai_32_1765459507.webp'], ['abrigos', 'Chaqueta Oliva', 'Abrigo estructurado de algodón', '₲319.000', 'https://static.tildacdn.com/tild3765-3830-4435-b561-373964333532/20240321___07518_web.jpg']]
    },
    'men.html': {
      label: 'Colección Hombre',
      categories: [['buzos', 'Buzos & sweaters'], ['camisas', 'Camisas'], ['denim', 'Denim'], ['esenciales', 'Esenciales']],
      items: [['buzos', 'Buzo Frontier', 'Frisa de algodón con interior suave', '₲249.000', 0], ['camisas', 'Camisa Sailor', 'Algodón texturado de calce relajado', '₲279.000', 1], ['buzos', 'Buzo Rugby', 'Tejido pesado de cuello alto', '₲229.000', 2], ['denim', 'Camisa Índigo', 'Denim liviano de terminación limpia', '₲269.000', 3], ['buzos', 'Buzo Freedom', 'French terry de tacto suave', '₲249.000', 4], ['camisas', 'Camisa Arena', 'Algodón liviano para todos los días', '₲269.000', 5], ['denim', 'Camisa Work', 'Denim clásico de algodón', '₲289.000', 6], ['esenciales', 'Camisa Flannel', 'Franela suave y confortable', '₲269.000', 7]]
    },
    'kids.html': {
      label: 'Colección Niños',
      categories: [['remeras', 'Remeras & conjuntos'], ['pantalones', 'Pantalones & shorts'], ['vestidos', 'Vestidos & faldas'], ['abrigos', 'Buzos & abrigos']],
      items: [['remeras', 'Remera Sol', 'Algodón suave para todos los días', '₲89.000', 'https://rags.com/cdn/shop/files/K01B8921.jpg?v=1724171172&width=1400'], ['remeras', 'Conjunto Play', 'Dos piezas livianas y cómodas', '₲149.000', 'https://www.pinkchicken.com/cdn/shop/files/Spring26_Flatlays_PinkChicken_07244_EDIT_e2b0f5b0-db3c-4d7b-bfa8-6b2a6bc029dc.png?crop=center&height=2048&v=1772130078&width=2048'], ['pantalones', 'Jogger Azul', 'Frisa flexible para jugar', '₲119.000', 'https://familiar.co.jp/cdn/shop/files/kids_01_75859bca-cb00-4952-a54b-110aa1d66344.jpg?v=1746759617&width=1800'], ['pantalones', 'Short Verde', 'Algodón fresco de verano', '₲99.000', 'https://www.minimondo.eu/cdn/shop/collections/neue-kollektion-bunt-f-r-m-dchen-und-jungen.png?v=1771307296'], ['vestidos', 'Vestido Rojo', 'Algodón con detalles de volantes', '₲149.000', 'https://image.hm.com/assets/hm/0e/f7/0ef7348e4ea92c17c90f151b2f123c25ba25918d.jpg?imwidth=2160'], ['vestidos', 'Vestido Garden', 'Estampa suave y cómoda', '₲139.000', 'https://www.minimondo.eu/cdn/shop/collections/neue-kollektion-bunt-f-r-m-dchen-und-jungen.png?v=1771307296'], ['abrigos', 'Buzo Cloud', 'Punto suave para días frescos', '₲139.000', 'https://static.showit.co/1200/kQnUkC8c7hUGAoNj8aynmA/154154/product-photography-australia-0952.jpg'], ['abrigos', 'Campera Mini', 'Abrigo acolchado y liviano', '₲179.000', 'https://outletbenetton.com/cdn/shop/files/140524_STILL_UCB_COMPOSIT_ADV_SS24_STUDIO_3_0016_368dd64c-5df9-4584-9ac3-183d1e08a363.jpg?v=1765970464&width=1920']]
    }
  };
  const currentCollection = collectionProducts[page];
  if (currentCollection) {
    const grid = document.querySelector('.catalog-content .product-grid');
    if (grid) grid.outerHTML = currentCollection.categories.map(([category, label]) => {
      const products = currentCollection.items.filter(item => item[0] === category);
      return `<section class="catalog-group" id="${category}"><div class="catalog-group-title"><h3>${label}</h3><span>${products.length} PRENDAS</span></div><div class="product-grid">${products.map(([, name, description, price, photo]) => `<article class="product-card"><div class="product-image"><img src="${typeof photo === 'number' ? productPhotos[photo] : photo}" alt="${name}" loading="lazy"><button class="add" type="button" aria-label="Agregar ${name}">+</button></div><div class="product-info"><h3>${name}</h3><p>${description}</p><strong>${price}</strong></div></article>`).join('')}</div></section>`;
    }).join('');
    document.querySelector('.catalog-content .section-top h2').textContent = currentCollection.label;
    document.querySelector('.catalog-content .section-top p').textContent = `${currentCollection.items.length} PRENDAS`;
    const categoryMenu = document.querySelector('.category-pills');
    if (categoryMenu) categoryMenu.innerHTML = `<a class="active" href="${page}">Ver toda la colección</a>${currentCollection.categories.map(([id, label]) => `<a href="#${id}">${label}</a>`).join('')}`;
  }
  if (page === 'index.html') {
    document.querySelectorAll('.product-card img').forEach((image, index) => { image.src = productPhotos[index % productPhotos.length]; });
    document.querySelectorAll('.category-card img').forEach((image, index) => { image.src = productPhotos[[1, 0, 4][index]]; });
    document.querySelector('.hero-image').style.backgroundImage = `url("${productPhotos[0]}")`;
    document.querySelector('.editorial-image').style.backgroundImage = `url("${productPhotos[6]}")`;
  }
  const imageFallbacks = { 'women.html': productPhotos[1], 'men.html': productPhotos[1], 'kids.html': productPhotos[1] };
  const recoverImage = image => {
    image.src = imageFallbacks[page] || 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&h=1200&q=85';
    image.alt = 'Prenda de la colección ATELIER';
  };
  document.querySelectorAll('img').forEach(image => {
    image.addEventListener('error', () => recoverImage(image), { once: true });
    if (image.complete && !image.naturalWidth) recoverImage(image);
  });

  document.body.insertAdjacentHTML('beforeend', `<div class="shop-overlay" hidden></div><aside class="cart-drawer" aria-label="Tu bolso" aria-hidden="true"><div class="drawer-heading"><div><p>TU BOLSO</p><h2>Elegiste bien.</h2></div><button class="drawer-close" aria-label="Cerrar bolso">×</button></div><div class="cart-items"></div><div class="cart-summary"><div><span>Subtotal</span><strong class="cart-total">₲0</strong></div><small>Envío y promociones se calculan en el checkout.</small><button class="shop-button checkout-button">Finalizar compra →</button></div></aside><section class="dialog product-dialog" role="dialog" aria-modal="true" aria-label="Detalle de producto" hidden><button class="dialog-close" aria-label="Cerrar">×</button><div class="product-dialog-content"></div></section><section class="dialog account-dialog" role="dialog" aria-modal="true" aria-label="Iniciar sesión o registrarse en ATELIER" hidden><button class="dialog-close" aria-label="Cerrar">×</button><div class="account-copy"><p>INGRESAR / REGISTRARSE</p><h2>Tu estilo, siempre cerca.</h2><span>Guardá tus datos para agilizar la compra. También podés seguir sin cuenta.</span></div><form class="account-form"><label>Nombre<input required name="name" autocomplete="name" placeholder="Tu nombre"></label><label>Correo<input required type="email" name="email" autocomplete="email" placeholder="hola@ejemplo.com"></label><button class="shop-button" type="submit">Crear cuenta / ingresar</button></form></section><section class="dialog checkout-dialog" role="dialog" aria-modal="true" aria-label="Checkout" hidden><button class="dialog-close" aria-label="Cerrar">×</button><div class="checkout-content"></div></section><div class="toast" role="status" aria-live="polite"></div>`);

  const overlay = document.querySelector('.shop-overlay'); const drawer = document.querySelector('.cart-drawer'); const cartCount = document.querySelector('.cart-count'); const cartItems = document.querySelector('.cart-items'); const cartTotal = document.querySelector('.cart-total'); const toast = document.querySelector('.toast'); const dialogs = [...document.querySelectorAll('.dialog')]; let toastTimer;
  function notify(message) { toast.textContent = message; toast.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => toast.classList.remove('show'), 2400); }
  function closeEverything() { drawer.classList.remove('open'); drawer.setAttribute('aria-hidden', 'true'); dialogs.forEach(dialog => { dialog.hidden = true; }); overlay.hidden = true; document.body.classList.remove('no-scroll'); }
  function openDialog(dialog) { closeEverything(); overlay.hidden = false; dialog.hidden = false; document.body.classList.add('no-scroll'); dialog.querySelector('input, button')?.focus(); }
  function openCart() { closeEverything(); overlay.hidden = false; drawer.classList.add('open'); drawer.setAttribute('aria-hidden', 'false'); document.body.classList.add('no-scroll'); }
  function renderCart() { const cart = getCart(); const quantity = cart.reduce((sum, item) => sum + item.quantity, 0); const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0); cartCount.textContent = quantity; cartCount.setAttribute('aria-label', `Abrir bolso, ${quantity} productos`); cartTotal.textContent = formatPrice(total); cartItems.innerHTML = cart.length ? cart.map(item => `<article class="cart-item"><img src="${item.image}" alt="${item.name}"><div><h3>${item.name}</h3><p>${item.description}</p><strong>${formatPrice(item.price)}</strong><span>Cantidad: ${item.quantity}</span></div><button class="remove-item" data-id="${item.id}" aria-label="Eliminar ${item.name}">×</button></article>`).join('') : `<div class="empty-cart"><span>◇</span><h3>Tu bolso está vacío.</h3><p>Elegí una prenda y la guardamos acá.</p><button class="text-button continue-shopping">Seguir explorando</button></div>`; }
  function addToCart(product) { const cart = getCart(); const existing = cart.find(item => item.id === product.id); existing ? existing.quantity += 1 : cart.push({ ...product, quantity: 1 }); saveCart(cart); renderCart(); notify(`${product.name} se agregó al bolso`); }
  function removeFromCart(id) { saveCart(getCart().filter(item => item.id !== id)); renderCart(); }
  const productMap = { 'Blazer sable': ['Mujer', 'Blazer de sastrería suave con caída relajada. Una pieza versátil para elevar cualquier conjunto.'], 'Jean recto oscuro': ['Mujer', 'Denim premium de tiro medio y silueta recta para usar todos los días.'], 'Camisa lino blanca': ['Mujer', 'Lino liviano y respirable, terminado con botones tono sobre tono.'], 'Sneaker pulse': ['Calzados', 'Sneaker de edición limitada con suela alta y máximo confort.'], 'Pantalón amplio': ['Mujer', 'Pantalón fluido de cintura alta que acompaña el movimiento.'], 'Remera grafito': ['Hombre', 'Algodón pesado con calce relajado y tacto suave.'], 'Short cargo': ['Hombre', 'Short utilitario con bolsillos funcionales y sarga resistente.'] };
  document.querySelectorAll('.product-card').forEach(card => { const name = card.querySelector('h3')?.textContent.trim() || 'Prenda ATELIER'; const description = card.querySelector('.product-info p')?.textContent.trim() || 'Nueva colección'; const price = readPrice(card.querySelector('strong')?.textContent); const image = card.querySelector('img')?.src || ''; const [category, detail] = productMap[name] || [page.includes('men') ? 'Hombre' : page.includes('kids') ? 'Niños' : 'Nueva colección', `${description}. Diseño pensado para combinar con tus esenciales favoritos.`]; const product = { id: `${name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${price}`, name, description, price, image, category, detail }; card.tabIndex = 0; card.setAttribute('role', 'button'); card.setAttribute('aria-label', `Ver detalles de ${name}`); card.querySelector('.add')?.addEventListener('click', event => { event.stopPropagation(); addToCart(product); }); const openProduct = () => { document.querySelector('.product-dialog-content').innerHTML = `<img src="${image}" alt="${name}"><div class="product-detail-copy"><p>${category.toUpperCase()} / NUEVA COLECCIÓN</p><h2>${name}</h2><strong>${formatPrice(price)}</strong><span>${detail}</span><div class="size-row"><b>Elegí tu talle</b><div><button>S</button><button>M</button><button>L</button><button>XL</button></div></div><button class="shop-button detail-add">Agregar al bolso →</button><small>Envío gratis desde ₲500.000 · Cambios fáciles</small></div>`; openDialog(document.querySelector('.product-dialog')); document.querySelector('.detail-add').addEventListener('click', () => { addToCart(product); closeEverything(); }); }; card.addEventListener('click', openProduct); card.addEventListener('keydown', event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); openProduct(); } }); });
  document.querySelector('.shop-menu')?.addEventListener('click', event => { const opened = nav.classList.toggle('open'); event.currentTarget.setAttribute('aria-expanded', opened); }); nav?.addEventListener('click', event => { if (event.target.tagName === 'A') nav.classList.remove('open'); }); document.querySelectorAll('.nav-subtoggle').forEach(button => button.addEventListener('click', () => button.parentElement.classList.toggle('sub-open'))); document.querySelector('.cart-count')?.addEventListener('click', openCart); document.querySelector('.drawer-close')?.addEventListener('click', closeEverything); document.querySelector('.account-button')?.addEventListener('click', () => openDialog(document.querySelector('.account-dialog'))); document.querySelectorAll('.dialog-close').forEach(button => button.addEventListener('click', closeEverything)); overlay.addEventListener('click', closeEverything); document.addEventListener('keydown', event => { if (event.key === 'Escape') closeEverything(); }); cartItems.addEventListener('click', event => { const remove = event.target.closest('.remove-item'); if (remove) removeFromCart(remove.dataset.id); if (event.target.closest('.continue-shopping')) closeEverything(); });
  document.querySelector('.account-form').addEventListener('submit', event => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); localStorage.setItem(USER_KEY, JSON.stringify(data)); closeEverything(); notify(`¡Hola, ${data.name}! Tu cuenta demo está lista.`); });
  document.querySelector('.checkout-button').addEventListener('click', () => { const cart = getCart(); if (!cart.length) return notify('Tu bolso todavía está vacío.'); const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0); const user = JSON.parse(localStorage.getItem(USER_KEY) || 'null'); document.querySelector('.checkout-content').innerHTML = `<div class="checkout-title"><p>CHECKOUT SEGURO / DEMO</p><h2>Un último paso.</h2><span>Esta compra es simulada: no se solicitarán ni procesarán pagos reales.</span></div><form class="checkout-form"><label>Nombre completo<input required name="name" value="${user?.name || ''}" placeholder="Nombre y apellido"></label><label>Correo electrónico<input required type="email" name="email" value="${user?.email || ''}" placeholder="hola@ejemplo.com"></label><label>Dirección de entrega<input required name="address" placeholder="Calle, número y ciudad"></label><label>Método de pago<select name="payment"><option>Transferencia bancaria</option><option>Tarjeta de crédito / débito</option><option>Pago contra entrega</option></select></label><div class="checkout-total"><span>Total estimado</span><strong>${formatPrice(total)}</strong></div><button class="shop-button" type="submit">Confirmar compra simulada →</button></form>`; openDialog(document.querySelector('.checkout-dialog')); document.querySelector('.checkout-form').addEventListener('submit', event => { event.preventDefault(); saveCart([]); renderCart(); document.querySelector('.checkout-content').innerHTML = `<div class="success-state"><span>✓</span><p>COMPRA CONFIRMADA</p><h2>¡Compra exitosa!</h2><div>Tu pedido demo <b>#AT-${String(Date.now()).slice(-5)}</b> fue creado. En una tienda real, este es el momento de enviar la confirmación por correo o WhatsApp.</div><button class="shop-button success-close">Volver a la tienda</button></div>`; document.querySelector('.success-close').addEventListener('click', closeEverything); }); });
  renderCart();
});
